### ISSUE TITLE
ViewPagerHelperUtils 里面复写ScollerDE  startScroll(int startX, int startY, int dx, int dy) 方法有问题

### ISSUE THREAD

**Issue by JeremyHwc** [LillteZheng/ViewPagerHelper#1]
问题1：

ViewPagerHelperUtils 里面复写Scoller的
        @Override
        public void startScroll(int startX, int startY, int dx, int dy) {
            super.startScroll(startX, startY, dx, time);
        }

这里这个方法应该不用复写，这里time替换了dy，dy应该是垂直移动的距离。

只用复写
       @Override
        public void startScroll(int startX, int startY, int dx, int dy, int duration) {
            super.startScroll(startX, startY, dx, dy, time);
        }
   
问题2：
   GlideViewpager类里面setPageListener，设置了setCurrentItem(bean.datas.size());
        setCurrentItem(0);  这里应该是设置了两次，应该只需要设置setCurrentItem(0)

**Comment by LillteZheng** [comment]
谢谢你的提醒，viewpager切换那里，我从其他项目复制过来了，没注意到，已经去掉了。第二个，也是从bannerviewpager 那里复制过来的，也是粗心大意；新的commit已改正过来；

**Comment by JeremyHwc** [comment]
TabIndicator里面setTabData里面在COLOR_TEXT里面有一个方法
textView.setTextColor(mDefaultColor, mChangeColor, mTextSize);
这个方法编译通不过  不知道是不是想用ColorStateList

**Comment by LillteZheng** [comment]
编译不过嘛？这个方法是设置 colortext 的初始颜色和移动时的颜色；代码如下：
/**
     * 公布出去，可以手动设置颜色和字体大小
     * @param defaultColor 默认颜色
     * @param changeColor  移动时的颜色
     * @param textsize
     */
    public void setTextColor(int defaultColor,int changeColor,int textsize){
        mDefaultColor = defaultColor;
        mChangeColor = changeColor;
        mPaint.setTextSize(textsize);
        invalidate();
    }
虽然方法名与 TextView 的 setTextColor一样了，但应该不会到错类才对，你看一下是不是外部引用错类了，TabIndicator 的这个方法，引用的是 ColorText 的方法；应该不会错才对，可否讲一下为何辩不过？原工程吗？这个方法名后期会修改掉

**Comment by JeremyHwc** [comment]
知道为什么了，我把ColorTextView里面的setTextColor这个方法修改成setTextColorAndSize了 不好意思不好意思

刚刚发现BannerViewPager里面的setPagerListener里面有两个setCurrentItem()方法。

**Comment by LillteZheng** [comment]
牛逼！中间修改比较多次，粗心了，改成 setCurrentItem(ViewPagerHelperUtils.LOOP_COUNT/2+bean.datas.size()); 就可以了，后期版本会更正

**Comment by LillteZheng** [comment]
谢谢反馈，已修正的问题就先关了
