### ISSUE TITLE
 只有一张图片，怎么禁止轮播图可滑动

### ISSUE THREAD

**Issue by chengmingyan** [LillteZheng/ViewPagerHelper#10]

**Comment by LillteZheng** [comment]
你的意思是，只有一张图的时候，不让它轮播是吧，这个我晚点会给个接口，让它可以设置多少张的时候才可以轮播

**Comment by LillteZheng** [comment]
你好，已经添加 banner_loop_max_count 变量，当数据大于这个数值时，才实现轮播，已经上传，可以在BannerViewPager这个控件的xml中，添加这个属性，数据小于这个值，就不会循环滚动了，稳定版等 #9 的问题解决了再一起上传
