### ISSUE TITLE
为啥我写的不自动轮播？缺少什么设置吗

### ISSUE THREAD

**Issue by chenni521** [LillteZheng/ViewPagerHelper#11]

**Comment by chenni521** [comment]
zsr:banner_isloop="true"  不是根据这个来 轮播的？我在fragment里面用不行

**Comment by chenni521** [comment]
zsr:banner_isloop="true" 不是根据这个来 轮播的？我用了 还是不轮播

**Comment by LillteZheng** [comment]
你好，这个变量就是用来管理轮播的，你可以参考一下 github 的配置；或者你可以把项目下载下来；进入  BannerActivity 这里，参考一下 demo 的例子

**Comment by chenni521** [comment]
你好  我就是照demo里面的  就是不自动轮播

**Comment by LillteZheng** [comment]
是你用gradle 的配置，还是把代码下载下来，修改成适合你的版本了？如果是修改了，或者demo下载下来了，可以调试一下，打印一下handler 是否有在动，我晚上回去再看一下

**Comment by chenni521** [comment]
好了  谢谢了

**Comment by LillteZheng** [comment]
谢谢反馈，配置问题先关了
