### ISSUE TITLE
能修改轮播图其他未选中的默认颜色不？

### ISSUE THREAD

**Issue by wanglianghai** [LillteZheng/ViewPagerHelper#12]

**Comment by LillteZheng** [comment]
你好，可以把你的需求说清楚点，不太明白你需要的功能

**Comment by wanglianghai** [comment]
就是那个小圆点，轮播图里的那个。用你的可以改变选中的小圆点的颜色，但是没选中的小圆点是灰色的，怎么样能把灰色改成其他颜色

**Comment by LillteZheng** [comment]
自定义属性那里，xxx_selector 这个属性，可以添加自己的selector，你写好selector，添加进去就可以了，不过颜色就要自己去调了

**Comment by wanglianghai** [comment]
<attr name="zoom_selector" format="reference"/> 
这个属性？这个只能调selector的颜色
我想调其他的selector的颜色，把灰色改成其他颜色，比如黑色

**Comment by wanglianghai** [comment]
zoom_selector="@drawable/bottom_circle"

**Comment by wanglianghai** [comment]
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_checked="true">
        <shape android:shape="oval">
            <solid android:color="@color/white" />
            <size android:width="10dp" android:height="10dp" />
        </shape>
    </item>
    <item android:state_checked="false">
        <shape android:shape="oval">
            <solid android:color="#000" />
            <size android:width="10dp" android:height="10dp" />
        </shape>
    </item>
</selector>
指示器未选中效果 没效果

**Comment by LillteZheng** [comment]
额，这个selector就包含了选中和未选中的状态的，参考一下普通的 selector：
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:state_selected="true">
        <shape android:shape="oval">
            <solid android:color="@color/colorAccent"/>
            <size android:width="8dp"
                android:height="8dp"/>
        </shape>
    </item>
     <item>
        <shape android:shape="oval">
            <solid android:color="@color/gray_cccc"/>
            <size android:width="8dp"
                android:height="8dp"/>
        </shape>
    </item>
</selector>

**Comment by wanglianghai** [comment]
可以了，谢谢，我发现是你的设置了透明度，黑色设置了还是灰的

**Comment by wanglianghai** [comment]
作者棒棒哒

**Comment by LillteZheng** [comment]
嗯，解决就好了，放大那块为了有效果，确实是做了透明度变化了
