### ISSUE TITLE
BannerView设置layout_height="wrap_content"无高度

### ISSUE THREAD

**Issue by wanglianghai** [LillteZheng/ViewPagerHelper#14]
<FrameLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:clipChildren="false">

        <com.zhengsr.viewpagerlib.view.BannerViewPager
            android:id="@+id/loop_viewpager"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
 android:layout_height="wrap_content"加载图片时无高度

**Comment by LillteZheng** [comment]
你肯定要设置高度啊，这个不计算子控件的大小然后重新填充父高度的，毕竟图片有大有小

**Comment by wanglianghai** [comment]
那想用后台的图片高度来决定，有没有什么办法

**Comment by LillteZheng** [comment]
你获取 BannerViewPager 这个实例的 layoutparams，重写它的 params.height 大小

**Comment by wanglianghai** [comment]
嗯，我试试，谢谢
