### ISSUE TITLE
ArcImageView 不支持gif的样子

### ISSUE THREAD

**Issue by w2282346548** [LillteZheng/ViewPagerHelper#16]

**Comment by LillteZheng** [comment]
是不支持的，因为 arcimageview  首先会把  drawable 转换成 bitmap，然后进行裁剪，而有些播放的 gif 的控件并不支持直转 bitmap，比如 glide。如果有可以直接转换成bitmap的，则 ArcImageView就可以用了

**Comment by LillteZheng** [comment]
感谢反馈
