### ISSUE TITLE
在layout中设置了轮播时间，但是页面中却不会自动轮播，请问是什么原因呢

### ISSUE THREAD

**Issue by LI5426629** [LillteZheng/ViewPagerHelper#19]

**Comment by LillteZheng** [comment]
banner_isloop 要设置为true

**Comment by LI5426629** [comment]
zsr:banner_isloop="true"
                zsr:banner_looptime="3000"
                zsr:banner_switchtime="600"
我是已经按照你的文档设置了这按个参数，但是没有效果

**Comment by LillteZheng** [comment]
手动正常吗 ？ 参考一下demo 中的layout：
https://github.com/LillteZheng/ViewPagerHelper/blob/master/app/src/main/res/layout/activity_loop.xml
或者下载整个工程看一下，是否少配置了什么

**Comment by LI5426629** [comment]
手动是正常的，我已经下载了demo进行参考，但是我现在没找找到问题点在哪

**Comment by LillteZheng** [comment]
demo 正常 ？ 如果正常，可以看一下 BannerView 中的Handler 是否正常跑

**Comment by LillteZheng** [comment]
issue 这般只反馈代码问题了，谢谢反馈
