### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zouzhenglu** [LillteZheng/ViewPagerHelper#2]
建议把pager跟indicator分开成两个包，
建议暴露图片加载接口，第三方包不要硬集成

**Comment by LillteZheng** [comment]
是分开成两个包的啊；glide 确实是我疏忽了，后期版本会放在 demo中，而不是在lib中；还有图片的加载不是公布出来了吗；setPageListener 的 getItemView中的view，就是整个 view 的接口，可以在这里更新，初始化的 json 也会重新加载

**Comment by zouzhenglu** [comment]
暴露图片加载接口跟第三方集成是同一个建议，如果lib里面没有用到图片加载，那就直接移到demo中就可以了。

**Comment by LillteZheng** [comment]
谢谢反馈
