### ISSUE TITLE
下面这个地方应该是PageXXX，不是PagerXXX吧。README文件写的

### ISSUE THREAD

**Issue by Lavned** [LillteZheng/ViewPagerHelper#20]
下面这个地方应该是PageXXX，不是Pager吧。README文件写的
看一个完整的配置：

 GlideViewPager viewPager = (GlideViewPager) findViewById(R.id.splase_viewpager);
        ZoomIndicator zoomIndicator = (ZoomIndicator) findViewById(R.id.splase_bottom_layout);
        Button button = (Button) findViewById(R.id.splase_start_btn);

        //先把本地的图片 id 装进 list 容器中
        List<Integer> images = new ArrayList<>();
        for (int i = 0; i < RES.length; i++) {
            images.add(RES[i]);

        }
        //配置pagerbean，这里主要是为了viewpager的指示器的作用，然后把最后一页的button也添加进来，注意记得写上泛型
        **PagerBean** bean = new **PagerBean**.Builder<Integer>()
                .setDataObjects(images)
                .setIndicator(zoomIndicator)
                .setOpenView(button)
                .builder();

        // 把数据添加到 viewpager中，并把view提供出来，这样除了方便调试，也不会出现一个view，多个
        // parent的问题，这里在轮播图比较明显
        viewPager.**setPagerListener**(bean, R.layout.image_layout, new **PagerHelperListener**<Integer>() {
            @Override
            public void getItemView(View view, Integer data) {
                //通过获取到这个view，你可以随意定制你的内容
                ImageView imageView = view.findViewById(R.id.icon);
                imageView.setImageResource(data);
            }
        });

**Comment by LillteZheng** [comment]
谢谢反馈，已修改
