### ISSUE TITLE
能否给TabIndicator配置一些属性，例如：两个标题之间的距离和设置可以滑动（类似今日头条的顶部导航栏）

### ISSUE THREAD

**Issue by wd548546** [LillteZheng/ViewPagerHelper#21]

**Comment by LillteZheng** [comment]
TabIndicator 目前不支持动态设置距离，是通过有多少个 子控件，然后用 weight = 1 去分配的；至于滑动的，目前还未做这个功能，后期可能会规划进去，你也可以download 下来自己修改，用 recyclerview 实现就可以了

**Comment by wd548546** [comment]
好的

**Comment by LillteZheng** [comment]
滑动已支持，是重写了它的touch事件，1.0 版本，可以下载下来体验一下

**Comment by wd548546** [comment]
好的，谢谢

**Comment by Xiosn** [comment]
如何设置Tabindicator俩标题之间的距离和居中？

**Comment by LillteZheng** [comment]
新库已支持 ： https://github.com/LillteZheng/FlowHelper
