### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by w296488320** [LillteZheng/ViewPagerHelper#24]
如果 有四个字 有2个字的 下面的 tops根本不对齐

**Comment by LillteZheng** [comment]
你是说超过字符超过控件大小吗？

**Comment by w296488320** [comment]
这个 上传不了 图片   比如    第一个 top是  你好你好  二三 是 你好    ，，， tops下面的导航条 和 字体不对齐

**Comment by LillteZheng** [comment]
子控件目前不支持自适应文字大小
