### ISSUE TITLE
indicator图片自定义

### ISSUE THREAD

**Issue by ZuoHailong** [LillteZheng/ViewPagerHelper#25]
indicator选中和未选中状态的图片能够分别定义就好了

**Comment by LillteZheng** [comment]
图片，什么图片呀，你把你的需求说一下，如果不错，后面我有时间，会去实现的

**Comment by ZuoHailong** [comment]
indicator，你的设定是选中状态放大，未选中状态缩小

**Comment by ZuoHailong** [comment]
indicator，你的设定是使用白色圆点，选中状态放大，未选中状态缩小
我的意思是，如果能够支持设定未选中状态显示icon1，选中状态显示icon2，就太好了

**Comment by LillteZheng** [comment]
好的，谢谢反馈，后面有时间会搞一下

**Comment by LillteZheng** [comment]
最近改库想了想，图片的缩放貌似没看到相关的示例和参考，效果都一般般；暂时先关闭这个，如果有好的示例，可再打开这个issue
