### ISSUE TITLE
如果只有一张图片或者两张怎么显示？一张的时候会显示三张一样的

### ISSUE THREAD

**Issue by q461935514** [LillteZheng/ViewPagerHelper#26]

**Comment by LillteZheng** [comment]
banner_loop_max_count  这个属性去定义是否要轮播

**Comment by q461935514** [comment]
这个不是在xml定义的么。如果我是网络获取的图片呢

**Comment by LillteZheng** [comment]
一样的，比如你的 max_count 为3，那网络的图片小于3张了，它也不会轮播；上面说错了，是超过这个值才会轮播；后面我找时间再把这些属性设置成动态设置吧

**Comment by q461935514** [comment]
对的需要一个动态设置。

**Comment by LillteZheng** [comment]
动态设置已添加，参考v1.5版本，谢谢
