### ISSUE TITLE
recycleview中不能轮播

### ISSUE THREAD

**Issue by lmwym** [LillteZheng/ViewPagerHelper#27]

**Comment by LillteZheng** [comment]
你好，recyclerview 中轮播是基本使用，请参考demo中的配置，添加到 recyclerview 的头部即可

**Comment by lmwym** [comment]
有recycleview的demo吗

**Comment by LillteZheng** [comment]
可以参考 BaseRecyclerViewAdapterHelper ，然后设置头部即可
