### ISSUE TITLE
TabIndicator无法平铺

### ISSUE THREAD

**Issue by zouzhenglu** [LillteZheng/ViewPagerHelper#3]
如题，tab的文字黏一起了

**Comment by LillteZheng** [comment]
你好，可以描述一下，你是怎么配置导致的吗，这样方便我查问题，谢谢

**Comment by zouzhenglu** [comment]
就跟你的demo一样写，然后就黏一起了，我想要实现的是，一行只有三个tab，然后平分宽度，好像没有找到这个设置属性。
还有，那个切换tab的时候，三角形移动动画不流畅，会颤抖

**Comment by zouzhenglu** [comment]
`    <com.zhiyecn.common.view.TabIndicator
        android:id="@+id/line_indicator"
        android:layout_width="match_parent"
        android:layout_height="@dimen/default_item_height_little"
        android:background="@color/colorAccent"
        app:tab_color="@color/white"
        app:tab_height="@dimen/dp_8"
        app:tab_show="true"
        app:tab_text_change_color="@color/text_color_white"
        app:tab_text_default_color="@color/text_color_white"
        app:tab_text_type="normaltext"
        app:tab_textsize="@dimen/default_textsize_16"
        app:tab_width="@dimen/dp_25"
        app:tap_type="tri"
        app:visiabel_size="2" />`

**Comment by zouzhenglu** [comment]
<com.zhiyecn.common.view.TabIndicator
        android:id="@+id/line_indicator"
        android:layout_width="match_parent"
        android:layout_height="@dimen/default_item_height_little"
        android:background="@color/colorAccent"
        app:tab_color="@color/white"
        app:tab_height="@dimen/dp_8"
        app:tab_show="true"
        app:tab_text_change_color="@color/text_color_white"
        app:tab_text_default_color="@color/text_color_white"
        app:tab_text_type="normaltext"
        app:tab_textsize="@dimen/default_textsize_16"
        app:tab_width="@dimen/dp_25"
        app:tap_type="tri"
        app:visiabel_size="2" />

**Comment by zouzhenglu** [comment]
tab_width好像是indicate三角形的宽度，如果是的话，建议命名改一下

**Comment by LillteZheng** [comment]
是这样的，如果你是通过setData加载数据的，那么在代码中，它会把textview 的宽度 = tab/count ，并且让textview 居中；然后 tab_width 不只是 三角形的，也有条状的大小，也是通过这个设置的。
另外，你说无法平铺的，我看一下你的设置，就visiable_size这里设置为2，那么只实现2个而已，其他的没什么问题，或者你可以下载整个代码，找到三角形的那个demo对比一下，是否有哪些差异，自己调试也可以。
颤抖这个，只能说模拟器的问题了，用手机就不会了，可以试试

**Comment by zouzhenglu** [comment]
两个三个都一样，我这里看到的只有setTabData没有setData，我自己copy了代码改了

**Comment by LillteZheng** [comment]
设置成 match_parent 的时候，应该没这个问题的才对；你可以先更新到 最新版的，因为TabIndicator的，然后再看一下，或者自己调试一下，为啥宽度不对。textview 的宽度设置再这里 params.width = mWidth / mCount;

**Comment by LillteZheng** [comment]
感谢反馈，该问题已解决，先关闭了
