### ISSUE TITLE
请问如何让幻灯片和指示器不从第一个图片开始播放

### ISSUE THREAD

**Issue by hexie2108** [LillteZheng/ViewPagerHelper#32]
比如有方法可以让幻灯片从第二个和第三个图开始播放的吗?

另外还有个问题是  在bannerViewPages.setPageListener 的getItemView方法里 有办法能获取到被触发的view对应的列表position吗?

谢谢.

**Comment by LillteZheng** [comment]
近期会对库进行升级，后面会支持的

**Comment by LillteZheng** [comment]
可以使用 setCurrentPosition 指定起始位置
