### ISSUE TITLE
你好，每次刷新的时候，indicator会成倍增加，这个怎么处理呢

### ISSUE THREAD

**Issue by Lavned** [LillteZheng/ViewPagerHelper#36]
是这么写的mBannerViewPager.addPageBean(mPageBean).addIndicator(indicator);
我改成
mBannerViewPager.addIndicator(null)
mBannerViewPager.addPageBean(mPageBean).addIndicator(indicator);
也没用，刷新一次，指示器会根据size多加几个

**Comment by LillteZheng** [comment]
if (viewHolderHead.bottomScaleLayout!=null){
viewHolderHead.bottomScaleLayout.removeAllViews();
}

先这样，remove 掉子控件，后面我弄个接口出来

**Comment by LillteZheng** [comment]
跟新到2.6即可，内部已经处理了，同时也修复了indicator 刷新后，位置和动画问题
