### ISSUE TITLE
BannerViewPager.setCurrentPosition() 在2.6 失效了

### ISSUE THREAD

**Issue by hexie2108** [LillteZheng/ViewPagerHelper#38]
在2.1 的时候表现正常, 可以正常改变默认显示的元素, 但是 把库升级到2.6后就无效了, 不管设置多少 都是默认显示0位置的元素.

另外请问有可以获取到 BannerViewPager当前显示item 的 position 方法吗?

**Comment by LhtIverson** [comment]
> 在2.1 的时候表现正常, 可以正常改变默认显示的元素, 但是 把库升级到2.6后就无效了, 不管设置多少 都是默认显示0位置的元素.
> 
> 另外请问有可以获取到 BannerViewPager当前显示item 的 position 方法吗?

问下 你遇到 更新到v2.6以后 轮播图不自动轮播的问题吗

**Comment by LillteZheng** [comment]
更新到 2.7即可，获取显示 item 的position，可以通过 viewpager 自带的getcurrentItem % datacount
