### ISSUE TITLE
更新库到v2.6 轮播问题

### ISSUE THREAD

**Issue by LhtIverson** [LillteZheng/ViewPagerHelper#39]
为什么更新库到2.6之后  进入页面轮播图不自动轮播了呢  然后进入二级页再返回首页 就开始自动轮播了  大佬 能回复下这是个什么情况吗

**Comment by LillteZheng** [comment]
代码怎么设置的，demo 中的都是能自动轮播的

**Comment by LhtIverson** [comment]
代码中就是正常设置的啊  更新之前是自动轮播的 然后刷新时候小圆点有个bug 刷新就加倍显示  然后我看了一下  您这边更新库了  我也跟着更新了一下 然后就不自动轮播了

**Comment by LillteZheng** [comment]
xml 和 java 部分的代码发一下呢，我现在有空，可以看一下

**Comment by LhtIverson** [comment]
<com.zhengsr.viewpagerlib.view.BannerViewPager
            android:id="@+id/normal_banner"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:banner_isAutoLoop="true"
            app:banner_looptime="3000"
            app:banner_switchtime="600"
            app:banner_transformer="mz"
            android:layout_marginStart="@dimen/dp_26"
            android:layout_marginEnd="@dimen/dp_26"/>

        <com.zhengsr.viewpagerlib.indicator.CircleIndicator
            android:id="@+id/normal_indicator"
            android:layout_width="wrap_content"
            android:layout_height="@dimen/dp_30"
            android:layout_gravity="center_horizontal|bottom"
            app:cir_canMove="false"
            app:cir_horizon_margin="@dimen/dp_10"
            app:cir_normalColor="@color/c_999"
            app:cir_selectedColor="@color/fff"
            app:cir_size="@dimen/dp5"
            app:cir_type="normal" />

**Comment by LhtIverson** [comment]
private void showBanner(List<BusinessSchoolHomeVoBean.BannerVoListBean> bannerVoList) {
        banner.addIndicator(indicator);
        banner.setPageListener(R.layout.loop_layout, bannerVoList, new PageHelperListener<BusinessSchoolHomeVoBean.BannerVoListBean>() {
            @Override
            public void bindView(View view, BusinessSchoolHomeVoBean.BannerVoListBean data, int position) {
                ImageView imageView = view.findViewById(R.id.loop_icon);
//                ImageUtils.loadNormalImage(getActivity(), data.getAdvertImage(), imageView);
                Glide.with(view)
                        .load(data.getPicUrl())
                        .into(imageView);
                //注册子控件事件
                addChildrenClick(view, R.id.loop_icon, position);
            }

//            @Override
//            public void onItemChildClick(View childView, final int data, int position) {
//                super.onItemChildClick(childView, data, position);
//            }
        });
    }

**Comment by LillteZheng** [comment]
嗯，我先把上一个issue解决一下，然后看一下你这个

**Comment by LhtIverson** [comment]
好的  谢谢

**Comment by LillteZheng** [comment]
没啥问题啊，我这边的apk 和demo也是这样配置的，能自动轮播，你检查一下代码呢

**Comment by LhtIverson** [comment]
那是咋回事呢 真奇怪啊

**Comment by LhtIverson** [comment]
我换到2.2版本 就没有问题不轮播的问题了 但是刷新小圆点就有问题了

**Comment by LillteZheng** [comment]
这样吧，你先看看和demo有什么区别，或者把你的代码弄个demo发我邮箱 845731923@qq.com

**Comment by LhtIverson** [comment]
我直接把我的xml和实现类给你打个包发过去吧

**Comment by LillteZheng** [comment]
弄成个工程，最好能复现

**Comment by LhtIverson** [comment]
主要是奇怪的很  我首页的轮播图 刚进入app不轮播  然后随便进一个二级页 再回首页  就开始轮播了

**Comment by LillteZheng** [comment]
你这发个视频很难看出什么的，你下载工程对比一下吧
