### ISSUE TITLE
资源,属性名加前缀

### ISSUE THREAD

**Issue by hss01248** [LillteZheng/ViewPagerHelper#5]
不然容易跟其他库冲突

比如text_color,text_size改成:
<attr name="vp_text_color" format="reference"/> 
<attr name="vp_text_size" format="dimension"/> 

另外,尽快升到gradle-plugin 3.0

**Comment by LillteZheng** [comment]
有道理，后期版本会跟进；3.0 我也想升啊，死了几次了就不敢了

**Comment by LillteZheng** [comment]
谢谢反馈，已修正问题先关了
