### ISSUE TITLE
侧拉栏 轮播图问题

### ISSUE THREAD

**Issue by zzz-97** [LillteZheng/ViewPagerHelper#6]
侧拉栏 拉出来  轮播图 有时候会轮到播放的图 不显示了 gai
该怎么办

**Comment by LillteZheng** [comment]
你好，我这边的项目也有用到侧边栏，但没出现你说的这种现象；你是怎么操作和配置的，图片是用网络还是本地的？可以把问题描述一下，我这边好重现看看

**Comment by zzz-97** [comment]
嗯。。就是 图片是网络的   配置跟着你的差不多 我的侧拉栏是会把 界面往右边推的 就像qq那种侧拉 然后他轮播动了 界面就自动弹回来了   然后轮播的时候 后面轮到的图 就是不出现了 那个指示器还是在动的 
可能是我自己的问题吧

**Comment by LillteZheng** [comment]
轮播图有个 pause和 resume 的方法，你可以在拉出来的时候，pause 让它不轮播，然后在监听回来之后，再让它轮播应该就解决了，可以试试

**Comment by LillteZheng** [comment]
感谢反馈
