### ISSUE TITLE
引导页Demo快速切换问题

### ISSUE THREAD

**Issue by gongjie** [LillteZheng/ViewPagerHelper#8]
引导页Demo快速切换时，开始体验按钮会不显示。

**Comment by HulkCheung** [comment]
我也遇到了，请问解决了这个问题了吗？

**Comment by LillteZheng** [comment]
这个问题是按钮在消失的时候，由于用了300ms的动画延时，所以快速滑动时，已经到了最后一页，但是动画姗姗来迟，又把它给弄消失了。已经处理了，可以更新一下

**Comment by LillteZheng** [comment]
谢谢反馈，已修正问题就先关了
