### ISSUE TITLE
onPause 方法有问题

### ISSUE THREAD

**Issue by xiaomsh** [LillteZheng/ViewPagerHelper#9]
如题
if (!isFocused()) 
if (isFirst) 
2个判断错了

希望尽快解决吧

还有个隐藏的比较深的 bug ，会白屏
具体操作就是下拉刷新，轮播图滑出屏幕，多操作几次，轮播图就自动变白屏

**Comment by LillteZheng** [comment]
好的，谢谢你的反馈，这几天项目比较紧，我晚上下班回去看看

**Comment by LillteZheng** [comment]
hi,关于onPause 和 onResume 的方法，已经修复，目前已经上传，但你说得这个白屏问题，我这边用了下啦方式，并没有模拟到这个现象，我用的布局是listview的多布局形式，你那边是怎么写的，可以描述一下吗，或者传个demo上来，我这边看一下，谢谢。
